//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackingClassLibrary.SetRGAService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReasonCategoryDTO", Namespace="http://schemas.datacontract.org/2004/07/KrausWarehouseServices.DTO.RMA")]
    [System.SerializableAttribute()]
    public partial class ReasonCategoryDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ReasonCatIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ReasonIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ReasonCatID {
            get {
                return this.ReasonCatIDField;
            }
            set {
                if ((this.ReasonCatIDField.Equals(value) != true)) {
                    this.ReasonCatIDField = value;
                    this.RaisePropertyChanged("ReasonCatID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ReasonID {
            get {
                return this.ReasonIDField;
            }
            set {
                if ((this.ReasonIDField.Equals(value) != true)) {
                    this.ReasonIDField = value;
                    this.RaisePropertyChanged("ReasonID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReasonsDTO", Namespace="http://schemas.datacontract.org/2004/07/KrausWarehouseServices.DTO.RMA")]
    [System.SerializableAttribute()]
    public partial class ReasonsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReasonFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ReasonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReasonPointsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReasonFlag {
            get {
                return this.ReasonFlagField;
            }
            set {
                if ((this.ReasonFlagField.Equals(value) != true)) {
                    this.ReasonFlagField = value;
                    this.RaisePropertyChanged("ReasonFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ReasonID {
            get {
                return this.ReasonIDField;
            }
            set {
                if ((this.ReasonIDField.Equals(value) != true)) {
                    this.ReasonIDField = value;
                    this.RaisePropertyChanged("ReasonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReasonPoints {
            get {
                return this.ReasonPointsField;
            }
            set {
                if ((this.ReasonPointsField.Equals(value) != true)) {
                    this.ReasonPointsField = value;
                    this.RaisePropertyChanged("ReasonPoints");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnDTO", Namespace="http://schemas.datacontract.org/2004/07/KrausWarehouseServices.DTO.RMA")]
    [System.SerializableAttribute()]
    public partial class ReturnDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatesDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerName1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerName2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> DecisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DeliveryDatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Exported_in_ERPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PONumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProgressFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RGAROWIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RMANumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> RMAStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Ready_To_ExportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReturnDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ReturnIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ScannedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Setting_Wty_DaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShipDate_ScanDate_Days_DiffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipmentNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendoeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendorNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Warranty_STAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Wrong_RMA_FlgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address3 {
            get {
                return this.Address3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address3Field, value) != true)) {
                    this.Address3Field = value;
                    this.RaisePropertyChanged("Address3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallTag {
            get {
                return this.CallTagField;
            }
            set {
                if ((object.ReferenceEquals(this.CallTagField, value) != true)) {
                    this.CallTagField = value;
                    this.RaisePropertyChanged("CallTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatesDate {
            get {
                return this.CreatesDateField;
            }
            set {
                if ((this.CreatesDateField.Equals(value) != true)) {
                    this.CreatesDateField = value;
                    this.RaisePropertyChanged("CreatesDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName1 {
            get {
                return this.CustomerName1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerName1Field, value) != true)) {
                    this.CustomerName1Field = value;
                    this.RaisePropertyChanged("CustomerName1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName2 {
            get {
                return this.CustomerName2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerName2Field, value) != true)) {
                    this.CustomerName2Field = value;
                    this.RaisePropertyChanged("CustomerName2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> Decision {
            get {
                return this.DecisionField;
            }
            set {
                if ((this.DecisionField.Equals(value) != true)) {
                    this.DecisionField = value;
                    this.RaisePropertyChanged("Decision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DeliveryDat {
            get {
                return this.DeliveryDatField;
            }
            set {
                if ((this.DeliveryDatField.Equals(value) != true)) {
                    this.DeliveryDatField = value;
                    this.RaisePropertyChanged("DeliveryDat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpirationDate {
            get {
                return this.ExpirationDateField;
            }
            set {
                if ((this.ExpirationDateField.Equals(value) != true)) {
                    this.ExpirationDateField = value;
                    this.RaisePropertyChanged("ExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Exported_in_ERP {
            get {
                return this.Exported_in_ERPField;
            }
            set {
                if ((this.Exported_in_ERPField.Equals(value) != true)) {
                    this.Exported_in_ERPField = value;
                    this.RaisePropertyChanged("Exported_in_ERP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber {
            get {
                return this.OrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNumberField, value) != true)) {
                    this.OrderNumberField = value;
                    this.RaisePropertyChanged("OrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PONumber {
            get {
                return this.PONumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PONumberField, value) != true)) {
                    this.PONumberField = value;
                    this.RaisePropertyChanged("PONumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProgressFlag {
            get {
                return this.ProgressFlagField;
            }
            set {
                if ((this.ProgressFlagField.Equals(value) != true)) {
                    this.ProgressFlagField = value;
                    this.RaisePropertyChanged("ProgressFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RGAROWID {
            get {
                return this.RGAROWIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RGAROWIDField, value) != true)) {
                    this.RGAROWIDField = value;
                    this.RaisePropertyChanged("RGAROWID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RMANumber {
            get {
                return this.RMANumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RMANumberField, value) != true)) {
                    this.RMANumberField = value;
                    this.RaisePropertyChanged("RMANumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> RMAStatus {
            get {
                return this.RMAStatusField;
            }
            set {
                if ((this.RMAStatusField.Equals(value) != true)) {
                    this.RMAStatusField = value;
                    this.RaisePropertyChanged("RMAStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Ready_To_Export {
            get {
                return this.Ready_To_ExportField;
            }
            set {
                if ((this.Ready_To_ExportField.Equals(value) != true)) {
                    this.Ready_To_ExportField = value;
                    this.RaisePropertyChanged("Ready_To_Export");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReturnDate {
            get {
                return this.ReturnDateField;
            }
            set {
                if ((this.ReturnDateField.Equals(value) != true)) {
                    this.ReturnDateField = value;
                    this.RaisePropertyChanged("ReturnDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ReturnID {
            get {
                return this.ReturnIDField;
            }
            set {
                if ((this.ReturnIDField.Equals(value) != true)) {
                    this.ReturnIDField = value;
                    this.RaisePropertyChanged("ReturnID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnReason {
            get {
                return this.ReturnReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnReasonField, value) != true)) {
                    this.ReturnReasonField = value;
                    this.RaisePropertyChanged("ReturnReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ScannedDate {
            get {
                return this.ScannedDateField;
            }
            set {
                if ((this.ScannedDateField.Equals(value) != true)) {
                    this.ScannedDateField = value;
                    this.RaisePropertyChanged("ScannedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Setting_Wty_Days {
            get {
                return this.Setting_Wty_DaysField;
            }
            set {
                if ((this.Setting_Wty_DaysField.Equals(value) != true)) {
                    this.Setting_Wty_DaysField = value;
                    this.RaisePropertyChanged("Setting_Wty_Days");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShipDate_ScanDate_Days_Diff {
            get {
                return this.ShipDate_ScanDate_Days_DiffField;
            }
            set {
                if ((this.ShipDate_ScanDate_Days_DiffField.Equals(value) != true)) {
                    this.ShipDate_ScanDate_Days_DiffField = value;
                    this.RaisePropertyChanged("ShipDate_ScanDate_Days_Diff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipmentNumber {
            get {
                return this.ShipmentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipmentNumberField, value) != true)) {
                    this.ShipmentNumberField = value;
                    this.RaisePropertyChanged("ShipmentNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((this.UpdatedByField.Equals(value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VendoeName {
            get {
                return this.VendoeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VendoeNameField, value) != true)) {
                    this.VendoeNameField = value;
                    this.RaisePropertyChanged("VendoeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VendorNumber {
            get {
                return this.VendorNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.VendorNumberField, value) != true)) {
                    this.VendorNumberField = value;
                    this.RaisePropertyChanged("VendorNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Warranty_STA {
            get {
                return this.Warranty_STAField;
            }
            set {
                if ((object.ReferenceEquals(this.Warranty_STAField, value) != true)) {
                    this.Warranty_STAField = value;
                    this.RaisePropertyChanged("Warranty_STA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Wrong_RMA_Flg {
            get {
                return this.Wrong_RMA_FlgField;
            }
            set {
                if ((object.ReferenceEquals(this.Wrong_RMA_FlgField, value) != true)) {
                    this.Wrong_RMA_FlgField = value;
                    this.RaisePropertyChanged("Wrong_RMA_Flg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnDetailsDTO", Namespace="http://schemas.datacontract.org/2004/07/KrausWarehouseServices.DTO.RMA")]
    [System.SerializableAttribute()]
    public partial class ReturnDetailsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DeliveredQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExpectedQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsManuallyAddedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsSkuScannedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LineTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RGADROWIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ReturnDetailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ReturnIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ReturnLinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReturnQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SKU_Qty_SeqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SKU_Reason_Total_PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SKU_SequenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKU_StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SalesPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ShipmentLinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TCLCOD_0Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrackingNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpadatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UpdatedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeliveredQty {
            get {
                return this.DeliveredQtyField;
            }
            set {
                if ((this.DeliveredQtyField.Equals(value) != true)) {
                    this.DeliveredQtyField = value;
                    this.RaisePropertyChanged("DeliveredQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExpectedQty {
            get {
                return this.ExpectedQtyField;
            }
            set {
                if ((this.ExpectedQtyField.Equals(value) != true)) {
                    this.ExpectedQtyField = value;
                    this.RaisePropertyChanged("ExpectedQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsManuallyAdded {
            get {
                return this.IsManuallyAddedField;
            }
            set {
                if ((this.IsManuallyAddedField.Equals(value) != true)) {
                    this.IsManuallyAddedField = value;
                    this.RaisePropertyChanged("IsManuallyAdded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsSkuScanned {
            get {
                return this.IsSkuScannedField;
            }
            set {
                if ((this.IsSkuScannedField.Equals(value) != true)) {
                    this.IsSkuScannedField = value;
                    this.RaisePropertyChanged("IsSkuScanned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LineType {
            get {
                return this.LineTypeField;
            }
            set {
                if ((this.LineTypeField.Equals(value) != true)) {
                    this.LineTypeField = value;
                    this.RaisePropertyChanged("LineType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIDField, value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductStatus {
            get {
                return this.ProductStatusField;
            }
            set {
                if ((this.ProductStatusField.Equals(value) != true)) {
                    this.ProductStatusField = value;
                    this.RaisePropertyChanged("ProductStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RGADROWID {
            get {
                return this.RGADROWIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RGADROWIDField, value) != true)) {
                    this.RGADROWIDField = value;
                    this.RaisePropertyChanged("RGADROWID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ReturnDetailID {
            get {
                return this.ReturnDetailIDField;
            }
            set {
                if ((this.ReturnDetailIDField.Equals(value) != true)) {
                    this.ReturnDetailIDField = value;
                    this.RaisePropertyChanged("ReturnDetailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ReturnID {
            get {
                return this.ReturnIDField;
            }
            set {
                if ((this.ReturnIDField.Equals(value) != true)) {
                    this.ReturnIDField = value;
                    this.RaisePropertyChanged("ReturnID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ReturnLines {
            get {
                return this.ReturnLinesField;
            }
            set {
                if ((this.ReturnLinesField.Equals(value) != true)) {
                    this.ReturnLinesField = value;
                    this.RaisePropertyChanged("ReturnLines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReturnQty {
            get {
                return this.ReturnQtyField;
            }
            set {
                if ((this.ReturnQtyField.Equals(value) != true)) {
                    this.ReturnQtyField = value;
                    this.RaisePropertyChanged("ReturnQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKUNumber {
            get {
                return this.SKUNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUNumberField, value) != true)) {
                    this.SKUNumberField = value;
                    this.RaisePropertyChanged("SKUNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SKU_Qty_Seq {
            get {
                return this.SKU_Qty_SeqField;
            }
            set {
                if ((this.SKU_Qty_SeqField.Equals(value) != true)) {
                    this.SKU_Qty_SeqField = value;
                    this.RaisePropertyChanged("SKU_Qty_Seq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SKU_Reason_Total_Points {
            get {
                return this.SKU_Reason_Total_PointsField;
            }
            set {
                if ((this.SKU_Reason_Total_PointsField.Equals(value) != true)) {
                    this.SKU_Reason_Total_PointsField = value;
                    this.RaisePropertyChanged("SKU_Reason_Total_Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SKU_Sequence {
            get {
                return this.SKU_SequenceField;
            }
            set {
                if ((this.SKU_SequenceField.Equals(value) != true)) {
                    this.SKU_SequenceField = value;
                    this.RaisePropertyChanged("SKU_Sequence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU_Status {
            get {
                return this.SKU_StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.SKU_StatusField, value) != true)) {
                    this.SKU_StatusField = value;
                    this.RaisePropertyChanged("SKU_Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SalesPrice {
            get {
                return this.SalesPriceField;
            }
            set {
                if ((this.SalesPriceField.Equals(value) != true)) {
                    this.SalesPriceField = value;
                    this.RaisePropertyChanged("SalesPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ShipmentLines {
            get {
                return this.ShipmentLinesField;
            }
            set {
                if ((this.ShipmentLinesField.Equals(value) != true)) {
                    this.ShipmentLinesField = value;
                    this.RaisePropertyChanged("ShipmentLines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TCLCOD_0 {
            get {
                return this.TCLCOD_0Field;
            }
            set {
                if ((object.ReferenceEquals(this.TCLCOD_0Field, value) != true)) {
                    this.TCLCOD_0Field = value;
                    this.RaisePropertyChanged("TCLCOD_0");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrackingNumber {
            get {
                return this.TrackingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackingNumberField, value) != true)) {
                    this.TrackingNumberField = value;
                    this.RaisePropertyChanged("TrackingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpadatedDate {
            get {
                return this.UpadatedDateField;
            }
            set {
                if ((this.UpadatedDateField.Equals(value) != true)) {
                    this.UpadatedDateField = value;
                    this.RaisePropertyChanged("UpadatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((this.UpdatedByField.Equals(value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnImagesDTO", Namespace="http://schemas.datacontract.org/2004/07/KrausWarehouseServices.DTO.RMA")]
    [System.SerializableAttribute()]
    public partial class ReturnImagesDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ReturnDetailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ReturnImageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUImagePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UpadatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpadatedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ReturnDetailID {
            get {
                return this.ReturnDetailIDField;
            }
            set {
                if ((this.ReturnDetailIDField.Equals(value) != true)) {
                    this.ReturnDetailIDField = value;
                    this.RaisePropertyChanged("ReturnDetailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ReturnImageID {
            get {
                return this.ReturnImageIDField;
            }
            set {
                if ((this.ReturnImageIDField.Equals(value) != true)) {
                    this.ReturnImageIDField = value;
                    this.RaisePropertyChanged("ReturnImageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKUImagePath {
            get {
                return this.SKUImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUImagePathField, value) != true)) {
                    this.SKUImagePathField = value;
                    this.RaisePropertyChanged("SKUImagePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UpadatedBy {
            get {
                return this.UpadatedByField;
            }
            set {
                if ((this.UpadatedByField.Equals(value) != true)) {
                    this.UpadatedByField = value;
                    this.RaisePropertyChanged("UpadatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpadatedDate {
            get {
                return this.UpadatedDateField;
            }
            set {
                if ((this.UpadatedDateField.Equals(value) != true)) {
                    this.UpadatedDateField = value;
                    this.RaisePropertyChanged("UpadatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SKUReasonsDTO", Namespace="http://schemas.datacontract.org/2004/07/KrausWarehouseServices.DTO.RMA")]
    [System.SerializableAttribute()]
    public partial class SKUReasonsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ReasonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ReturnDetailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SKUReasonIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ReasonID {
            get {
                return this.ReasonIDField;
            }
            set {
                if ((this.ReasonIDField.Equals(value) != true)) {
                    this.ReasonIDField = value;
                    this.RaisePropertyChanged("ReasonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ReturnDetailID {
            get {
                return this.ReturnDetailIDField;
            }
            set {
                if ((this.ReturnDetailIDField.Equals(value) != true)) {
                    this.ReturnDetailIDField = value;
                    this.RaisePropertyChanged("ReturnDetailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SKUReasonID {
            get {
                return this.SKUReasonIDField;
            }
            set {
                if ((this.SKUReasonIDField.Equals(value) != true)) {
                    this.SKUReasonIDField = value;
                    this.RaisePropertyChanged("SKUReasonID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTO", Namespace="http://schemas.datacontract.org/2004/07/KrausWarehouseServices.DTO.Shipping")]
    [System.SerializableAttribute()]
    public partial class UserDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UpdatedbyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UserJoiningDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDateTime {
            get {
                return this.CreatedDateTimeField;
            }
            set {
                if ((this.CreatedDateTimeField.Equals(value) != true)) {
                    this.CreatedDateTimeField = value;
                    this.RaisePropertyChanged("CreatedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RoleID {
            get {
                return this.RoleIDField;
            }
            set {
                if ((this.RoleIDField.Equals(value) != true)) {
                    this.RoleIDField = value;
                    this.RaisePropertyChanged("RoleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedDateTime {
            get {
                return this.UpdatedDateTimeField;
            }
            set {
                if ((this.UpdatedDateTimeField.Equals(value) != true)) {
                    this.UpdatedDateTimeField = value;
                    this.RaisePropertyChanged("UpdatedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Updatedby {
            get {
                return this.UpdatedbyField;
            }
            set {
                if ((this.UpdatedbyField.Equals(value) != true)) {
                    this.UpdatedbyField = value;
                    this.RaisePropertyChanged("Updatedby");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserAddress {
            get {
                return this.UserAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.UserAddressField, value) != true)) {
                    this.UserAddressField = value;
                    this.RaisePropertyChanged("UserAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserFullName {
            get {
                return this.UserFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserFullNameField, value) != true)) {
                    this.UserFullNameField = value;
                    this.RaisePropertyChanged("UserFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UserJoiningDate {
            get {
                return this.UserJoiningDateField;
            }
            set {
                if ((this.UserJoiningDateField.Equals(value) != true)) {
                    this.UserJoiningDateField = value;
                    this.RaisePropertyChanged("UserJoiningDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPassword {
            get {
                return this.UserPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPasswordField, value) != true)) {
                    this.UserPasswordField = value;
                    this.RaisePropertyChanged("UserPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RMAAuditDTO", Namespace="http://schemas.datacontract.org/2004/07/KrausWarehouseServices.DTO.RMA")]
    [System.SerializableAttribute()]
    public partial class RMAAuditDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ActionTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserLogIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ActionTime {
            get {
                return this.ActionTimeField;
            }
            set {
                if ((this.ActionTimeField.Equals(value) != true)) {
                    this.ActionTimeField = value;
                    this.RaisePropertyChanged("ActionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionType {
            get {
                return this.ActionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionTypeField, value) != true)) {
                    this.ActionTypeField = value;
                    this.RaisePropertyChanged("ActionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionValue {
            get {
                return this.ActionValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionValueField, value) != true)) {
                    this.ActionValueField = value;
                    this.RaisePropertyChanged("ActionValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserLogID {
            get {
                return this.UserLogIDField;
            }
            set {
                if ((this.UserLogIDField.Equals(value) != true)) {
                    this.UserLogIDField = value;
                    this.RaisePropertyChanged("UserLogID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnedSKUReasonPointsDTO", Namespace="http://schemas.datacontract.org/2004/07/KrausWarehouseServices.DTO.RMA")]
    [System.SerializableAttribute()]
    public partial class ReturnedSKUReasonPointsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Reason_ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> ReturnDetailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> ReturnIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SkuSequenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason_Value {
            get {
                return this.Reason_ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.Reason_ValueField, value) != true)) {
                    this.Reason_ValueField = value;
                    this.RaisePropertyChanged("Reason_Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ReturnDetailID {
            get {
                return this.ReturnDetailIDField;
            }
            set {
                if ((this.ReturnDetailIDField.Equals(value) != true)) {
                    this.ReturnDetailIDField = value;
                    this.RaisePropertyChanged("ReturnDetailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ReturnID {
            get {
                return this.ReturnIDField;
            }
            set {
                if ((this.ReturnIDField.Equals(value) != true)) {
                    this.ReturnIDField = value;
                    this.RaisePropertyChanged("ReturnID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUField, value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SkuSequence {
            get {
                return this.SkuSequenceField;
            }
            set {
                if ((this.SkuSequenceField.Equals(value) != true)) {
                    this.SkuSequenceField = value;
                    this.RaisePropertyChanged("SkuSequence");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RMACommentDTO", Namespace="http://schemas.datacontract.org/2004/07/KrausWarehouseServices.DTO.RMA")]
    [System.SerializableAttribute()]
    public partial class RMACommentDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CommentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RMACommentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> ReturnIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CommentDate {
            get {
                return this.CommentDateField;
            }
            set {
                if ((this.CommentDateField.Equals(value) != true)) {
                    this.CommentDateField = value;
                    this.RaisePropertyChanged("CommentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RMACommentID {
            get {
                return this.RMACommentIDField;
            }
            set {
                if ((this.RMACommentIDField.Equals(value) != true)) {
                    this.RMACommentIDField = value;
                    this.RaisePropertyChanged("RMACommentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ReturnID {
            get {
                return this.ReturnIDField;
            }
            set {
                if ((this.ReturnIDField.Equals(value) != true)) {
                    this.ReturnIDField = value;
                    this.RaisePropertyChanged("ReturnID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SetRGAService.ISave")]
    public interface ISave {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISave/ReasonCategory", ReplyAction="http://tempuri.org/ISave/ReasonCategoryResponse")]
        bool ReasonCategory(PackingClassLibrary.SetRGAService.ReasonCategoryDTO reasonCat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISave/Reasons", ReplyAction="http://tempuri.org/ISave/ReasonsResponse")]
        bool Reasons([System.ServiceModel.MessageParameterAttribute(Name="reasons")] PackingClassLibrary.SetRGAService.ReasonsDTO reasons1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISave/Return", ReplyAction="http://tempuri.org/ISave/ReturnResponse")]
        bool Return(PackingClassLibrary.SetRGAService.ReturnDTO _return);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISave/ReturnByPOnmber", ReplyAction="http://tempuri.org/ISave/ReturnByPOnmberResponse")]
        bool ReturnByPOnmber(PackingClassLibrary.SetRGAService.ReturnDTO _return);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISave/ReturnByRGANumber", ReplyAction="http://tempuri.org/ISave/ReturnByRGANumberResponse")]
        bool ReturnByRGANumber(PackingClassLibrary.SetRGAService.ReturnDTO _return);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISave/ReturnDetails", ReplyAction="http://tempuri.org/ISave/ReturnDetailsResponse")]
        bool ReturnDetails(PackingClassLibrary.SetRGAService.ReturnDetailsDTO returndetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISave/ReturnImages", ReplyAction="http://tempuri.org/ISave/ReturnImagesResponse")]
        bool ReturnImages([System.ServiceModel.MessageParameterAttribute(Name="returnimages")] PackingClassLibrary.SetRGAService.ReturnImagesDTO returnimages1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISave/SKUReasons", ReplyAction="http://tempuri.org/ISave/SKUReasonsResponse")]
        bool SKUReasons(PackingClassLibrary.SetRGAService.SKUReasonsDTO SKU);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISave/SKUReasons1", ReplyAction="http://tempuri.org/ISave/SKUReasons1Response")]
        bool SKUReasons1(PackingClassLibrary.SetRGAService.SKUReasonsDTO SKU);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISave/User", ReplyAction="http://tempuri.org/ISave/UserResponse")]
        bool User([System.ServiceModel.MessageParameterAttribute(Name="user")] PackingClassLibrary.SetRGAService.UserDTO user1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISave/UpsertAudit", ReplyAction="http://tempuri.org/ISave/UpsertAuditResponse")]
        bool UpsertAudit(PackingClassLibrary.SetRGAService.RMAAuditDTO audit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISave/ReturnedSKUPoints", ReplyAction="http://tempuri.org/ISave/ReturnedSKUPointsResponse")]
        bool ReturnedSKUPoints(PackingClassLibrary.SetRGAService.ReturnedSKUReasonPointsDTO _returnedSkuPoints);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISave/InsertRMAComment", ReplyAction="http://tempuri.org/ISave/InsertRMACommentResponse")]
        bool InsertRMAComment(PackingClassLibrary.SetRGAService.RMACommentDTO _comment);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISaveChannel : PackingClassLibrary.SetRGAService.ISave, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveClient : System.ServiceModel.ClientBase<PackingClassLibrary.SetRGAService.ISave>, PackingClassLibrary.SetRGAService.ISave {
        
        public SaveClient() {
        }
        
        public SaveClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SaveClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaveClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaveClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ReasonCategory(PackingClassLibrary.SetRGAService.ReasonCategoryDTO reasonCat) {
            return base.Channel.ReasonCategory(reasonCat);
        }
        
        public bool Reasons(PackingClassLibrary.SetRGAService.ReasonsDTO reasons1) {
            return base.Channel.Reasons(reasons1);
        }
        
        public bool Return(PackingClassLibrary.SetRGAService.ReturnDTO _return) {
            return base.Channel.Return(_return);
        }
        
        public bool ReturnByPOnmber(PackingClassLibrary.SetRGAService.ReturnDTO _return) {
            return base.Channel.ReturnByPOnmber(_return);
        }
        
        public bool ReturnByRGANumber(PackingClassLibrary.SetRGAService.ReturnDTO _return) {
            return base.Channel.ReturnByRGANumber(_return);
        }
        
        public bool ReturnDetails(PackingClassLibrary.SetRGAService.ReturnDetailsDTO returndetail) {
            return base.Channel.ReturnDetails(returndetail);
        }
        
        public bool ReturnImages(PackingClassLibrary.SetRGAService.ReturnImagesDTO returnimages1) {
            return base.Channel.ReturnImages(returnimages1);
        }
        
        public bool SKUReasons(PackingClassLibrary.SetRGAService.SKUReasonsDTO SKU) {
            return base.Channel.SKUReasons(SKU);
        }
        
        public bool SKUReasons1(PackingClassLibrary.SetRGAService.SKUReasonsDTO SKU) {
            return base.Channel.SKUReasons1(SKU);
        }
        
        public bool User(PackingClassLibrary.SetRGAService.UserDTO user1) {
            return base.Channel.User(user1);
        }
        
        public bool UpsertAudit(PackingClassLibrary.SetRGAService.RMAAuditDTO audit) {
            return base.Channel.UpsertAudit(audit);
        }
        
        public bool ReturnedSKUPoints(PackingClassLibrary.SetRGAService.ReturnedSKUReasonPointsDTO _returnedSkuPoints) {
            return base.Channel.ReturnedSKUPoints(_returnedSkuPoints);
        }
        
        public bool InsertRMAComment(PackingClassLibrary.SetRGAService.RMACommentDTO _comment) {
            return base.Channel.InsertRMAComment(_comment);
        }
    }
}
