//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackingClassLibrary.DeleteService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DeleteService.IDelete")]
    public interface IDelete {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelete/PackageByShipmentNum", ReplyAction="http://tempuri.org/IDelete/PackageByShipmentNumResponse")]
        bool PackageByShipmentNum(string ShipmentNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelete/ShippingByPackingID", ReplyAction="http://tempuri.org/IDelete/ShippingByPackingIDResponse")]
        bool ShippingByPackingID(System.Guid PackingID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeleteChannel : PackingClassLibrary.DeleteService.IDelete, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteClient : System.ServiceModel.ClientBase<PackingClassLibrary.DeleteService.IDelete>, PackingClassLibrary.DeleteService.IDelete {
        
        public DeleteClient() {
        }
        
        public DeleteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeleteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeleteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeleteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool PackageByShipmentNum(string ShipmentNum) {
            return base.Channel.PackageByShipmentNum(ShipmentNum);
        }
        
        public bool ShippingByPackingID(System.Guid PackingID) {
            return base.Channel.ShippingByPackingID(PackingID);
        }
    }
}
